Feature crud class
gladguys/aluco-api pull request #15
Opened 2019-10-24 06:18 UTC by diCaminha

Close #6

2019-10-24 10:25 UTC, weslyh requested changes

2019-10-24 10:25 UTC, weslyh commented on src/main/java/com/gladguys/alucoapi/services/impl/ClassServiceImpl.java
> +			students.add(this.studentService.getById(dto.getId()));
Não seria interessante criar um método que buscasse logo todos os students de uma vez só, passando como parâmetro uma lista de IDs de Student, e no final dá apenas um `students.addAll` ? Por que dessa forma, ele ta indo no banco `studentDTOS.size() -1` vezes.

2019-10-24 10:42 UTC, diCaminha commented on src/main/java/com/gladguys/alucoapi/services/impl/ClassServiceImpl.java
> +			students.add(this.studentService.getById(dto.getId()));
Sim, concordo... mas isso vai ser pra fase de implementação customizada dos nossos metodos de get ( foi combinado q por enquanto deixarmos os get do spring data mesmo, mas devido a performance n iremos usa-los). 
Poreeeem, vale pesquisar algo pelo proprio jpa pra fazer essa busca com varios ids e analisar se n ta criando mt join doido. Valeu pela observação

2019-10-24 10:49 UTC, weslyh approved these changes

2019-10-27 20:36 UTC, lailsonbento commented on src/main/java/com/gladguys/alucoapi/controllers/ClassController.java
> +	public ResponseEntity<Set<ClassDTO>> getAllByTeacher(@PathVariable("teacherId") Long teacherId) {
Esse método não faz a mesma coisa do abaixo "getAll"? 
A diferença é que em um você manda o id e no outro você pega no token

2019-10-27 20:40 UTC, lailsonbento commented on src/main/java/com/gladguys/alucoapi/controllers/ClassController.java
> +			return ResponseEntity.status(HttpStatus.OK).body("turma removida com sucesso.");
Não seria melhor retornar um NO_CONTENT e sem body (Rodrigo falou que não tinha necessidade de retornar mensagem de sucesso), já que foi removido? Acho mais apropriado para esse tipo de situação

2019-10-27 20:42 UTC, lailsonbento commented on src/main/java/com/gladguys/alucoapi/controllers/ClassController.java
> +					"não foi encontrado a lista de estudantes a adicionar");
Mesma coisa do comentário acima, sobre a mensagem

2019-10-27 20:42 UTC, lailsonbento commented on src/main/java/com/gladguys/alucoapi/controllers/ClassController.java
> +			return ResponseEntity.ok("estudantes adicionados a classe ");
Melhor retornar um 201 (CREATED) não? E sem mensagem

2019-10-27 20:47 UTC, lailsonbento commented on src/main/java/com/gladguys/alucoapi/entities/Call.java
> +	private LocalDate date;
Adicionar @JsonFormat(pattern = "dd-MM-yyyy")

2019-10-27 20:50 UTC, lailsonbento commented on src/main/java/com/gladguys/alucoapi/controllers/ClassController.java
> +			ClassDTO classDTO = this.classService.saveOrUpdate(dto);
Retornar um CREATED

2019-10-27 20:51 UTC, lailsonbento commented on src/main/java/com/gladguys/alucoapi/controllers/ClassController.java
> +			return ResponseEntity.ok(classDTO);
Retornar HttpStatus.CREATED

2019-10-27 20:52 UTC, lailsonbento commented on src/main/java/com/gladguys/alucoapi/entities/Class.java
> +    private LocalDate creationDate;
Não seria bom formatar essa data aqui também?

2019-10-27 21:02 UTC, lailsonbento commented on src/main/java/com/gladguys/alucoapi/controllers/ClassController.java
> +			if(wrapper == null) return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(
Não seria bom verificar se a lista dentro está vazia?

2019-10-27 21:07 UTC, lailsonbento commented on src/main/java/com/gladguys/alucoapi/services/impl/ClassServiceImpl.java
> +		if (teacherId == null) throw new Exception();
Melhor fazer essa validação no Controller?

2019-10-27 21:07 UTC, lailsonbento commented on src/main/java/com/gladguys/alucoapi/services/impl/ClassServiceImpl.java
> +
Quebra de linha

2019-10-27 22:01 UTC, merged